maps:
  test:
    name: 'Test Map'
    location:
      world: world
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0
      pitch: 0.0

roles:
  murderer:
    name: '&4Murderer'
    goal: 'Kill all players'
  detective:
    name: '&9Detective'
    goal: 'Shoot the murderer'
  underdog:
    name: '&5Underdog'
    goal: 'Snowball the murderer'
  bystander:
    name: '&6Bystander'
    goal: 'Survive the murderer'
  dead:
    name: '&cDead'
    goal: 'Don''t get bored'

scoreboard:
  title: '&4&lMurder Mystery'
  lines:
    - '&7=-=-=-=-=-=-=-='
    - ''
    - '&aMap: &e%map%'
    - ''
    - '&aTime Left: &e%time%'
    - ''
    - '&aRole: &e%role%'
    - ''
    - '&aPlayers Alive: &e%alive%'
    - ''
    - '&aScore: &e%score%'
    - ''
    - '&7=-=-=-=-=-=-=-='

titles:
  start:
    title: '%role%'
    subtitle: 'Goal: %goal%'
  end:
    title: 'Game Over'
    subtitles:
      murderer_killed: 'The murderer was killed'
      all_killed: 'The murderer killed everyone'
      time_expired: 'The murderer ran out of time'

time:
  total: 300
  grace: 15
  grace_warning: '&6The grace period ends in %d seconds'
  grace_ended: '&6The grace period has ended'
  potato_warning: '&cThe Hot Potato will BURN in %d seconds'
  potato_burned: '&c&l%s was burnt to a crisp by a hot potato!'
  glow: 30
  potato: 60
  potato_countdown: 10

items:
  murderer:
    sword_name: '&4Murderer Knife'
  detective:
    bow_name: '&9Detective Bow'
    bow_dropped: '&9The bow has been dropped!'
    bow_pickedup: '&9The bow has been picked up!'
  potato:
    potato_name: '&5Hot Potato'
    potato_lore: '&7YAHOOHOOHOTHOT'

chance:
  hotpotato: 1
